### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok-extra#2]
* [x] Minimal surface node: option to do not generate any mesh (only output Surface); make it the default one.
* [x] Node(s) to generate "bending" VectorField from a) RbfSurface, b) NURBS surface, c) NURBS curve.
* [x] Differential operators for scalar and vector fields: gradient, divergence, Laplace, rotor.
* [x] "Marching squares" node that operates on textures. Implemented as "Image Field" node, that turns Image datablock into either Scalar Field or Vector Field. Marching Squares can be applied to any scalar field.

**Comment by vicdoval** [comment]
Maybe some of this could be integrated https://pymesh.readthedocs.io/en/latest/user_guide.html

**Comment by vicdoval** [comment]
This open many possibilities... maybe image processing? https://opensource.com/article/19/3/python-image-manipulation-tools :smile:

**Comment by portnov** [comment]
@vicdoval pymesh's installation instruction look a bit too complex even to me :)
As for image processing: do you have any scenarios of how this can be useful in Sverchok's area?
